### ISSUE TITLE
USER STORY: Add newsletter sign-up option

### ISSUE THREAD

**Issue by Rafaela-Wetzel** [Rafaela-Wetzel/Love-Sandwiches#3]
As a user I can enter my e-mail address so that I receive regular newsletter updates

## Acceptance Criteria:
* User can enter e-mail address 
* Newsletter is sent out
* There is a submit button
* There is another option to opt out of the newsletter

## Tasks:
- [ ] Create HTML sign up fields
- [ ] Style with CSS
- [ ] Add submit button
- [ ] Add opt out button
- [ ] Create newsletter forwarding
